### ISSUE TITLE
Tool seems to be outdated - can’t get it to function

### ISSUE THREAD

**Issue by eltesco1** [Jamal135/IndeedScraper#1]
Hi there, this tool seems to be exactly what I need for some research i am doing, however it fails for both indeed and seek. Possibly out of date for updated websites?

Would really like to use this for seek australia reviews of a company.

with seek I get the error: failed to determine review data

with indeed i get: Failed to grab url

any help you can give would be amazing!

**Comment by McWashr** [comment]
Yes it will be due to website updates, this hasn't been updated in a long time. I will investigate the code for Seek and see if it is repairable for you. =)

**Comment by McWashr** [comment]
Upon initial review this scraper is fundamentally broken for Seek (likely Indeed as well). Seek now dynamically loads reviews via JavaScript. This means direct browser interaction is required to load more than the first page of reviews. This repository relied upon BeautifulSoup to scrape reviews, which can only scrape static content. 

I will work on a rewrite today, using Selenium instead.

**Comment by eltesco1** [comment]
Thanks so much Jamal,

It seems to be the perfect tool.

**Comment by McWashr** [comment]
Cheers. As an update current version successfully scrapes data. I am working on improving the scraping and error handling, I then plan to add the CSV creation and a command line interface. Hopefully finished tomorrow.

https://github.com/Jamal135/indeed-and-seek-scraper/blob/main/seek_scraper.py

**Comment by eltesco1** [comment]
Amazing! cant wait to test!

**Comment by eltesco1** [comment]
Just checking, does this tool give a break-down of the individual review rating areas? See image
![image](https://github.com/Jamal135/indeed-and-seek-scraper/assets/12418837/d6b92ebc-aaf3-4eb0-9adc-4ced7c1ce265)

**Comment by McWashr** [comment]
I hadn't intended to add the individual ratings, though that actually seems quite useful. Should be easy to add, will explore.

**Comment by eltesco1** [comment]
Thanks Jamal, I am using this for a research project and this would give me incredible insights into several companies! Thank you so much for your time and help!

**Comment by McWashr** [comment]
No problem my friend, would love to see the outcomes of your research project one day. Good news I can get it easily. Here is the block of data we extract per review, it will be cleaned into a CSV.

['3.0', '', 'Benefits & perks', '', '2.0 out of 5', 'Career development', '', '1.0 out of 5', 'Work-life balance', '', '2.0 out of 5', 'Working environment', '', '3.0 out of 5', 'Management', '', '3.0 out of 5', 'Diversity & equal opportunity', '', '3.0 out of 5', 'Client Assistant', 'May 2023', 'Preston VIC 3072', '1 to 2 years in the role, ', 'Good job to get by.', 'The good things', 'The clothes discount.', 'The challenges', 'Lack of work / life balance as a casual and how little choice I had over total hours I worked.']

We have total rating, rating for each category, position, time of review, location (may vary in detail), time in role and current/former employee (both are optional though so may be NA). the pros, and the cons.

**Comment by eltesco1** [comment]
That looks perfect.

**Comment by McWashr** [comment]
Hey @eltesco1 I'd appreciate it if you give this a little spin. Use v0.3, install requirements, and put together whatever scape_config JSON file you need (test.json) should show you how to put the config JSON file together. 

Let me know if you have any issues. Right now it should all be working though it won't give you the nice CSV yet, it will just dump to a text file. I will just be doing some cleanup tomorrow and I will implement the CSV parser.

**Comment by eltesco1** [comment]
Updated Json, Installed requirements but getting an error:

C:\Users\Admin\Downloads\pyscrapify-main\pyscrapify-main>launcher.py
[-] Preparing to launch scraper...
[i] Generated output name: result_0
[?] Please select a scraper configuration: test.json
 > test.json

[-] Calling scraper launcher...
[!] ERROR: Unexpected error, scraper: Seek
No module named 'scrapers.Seek'
[!] TRACE:
  File "C:\Users\Admin\Downloads\pyscrapify-main\pyscrapify-main\utilities\scraper_controller.py", line 89, in scrape_launch
    scraper = ScraperBuilder.build(f'scrapers.{config.scraper_name}')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\pyscrapify-main\pyscrapify-main\utilities\scraper_builder.py", line 22, in build
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked

**Comment by eltesco1** [comment]
Updated Json, Installed requirements but getting an error:

[-] Preparing to launch scraper...
[i] Generated output name: result_0
[?] Please select a scraper configuration: test.json
 > test.json

[-] Calling scraper launcher...
[!] ERROR: Unexpected error, scraper: Seek
No module named 'scrapers.Seek'
[!] TRACE:
  File "C:\Users\Admin\Downloads\pyscrapify-main\pyscrapify-main\utilities\scraper_controller.py", line 89, in scrape_launch
    scraper = ScraperBuilder.build(f'scrapers.{config.scraper_name}')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\pyscrapify-main\pyscrapify-main\utilities\scraper_builder.py", line 22, in build
    module = importlib.import_module(module_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked

**Comment by McWashr** [comment]
Fixed, that was just a filename issue.

**Comment by McWashr** [comment]
Alright, pushing a working version commit now. I will close this issue, though I recognise it is almost certain some bugs exist in this repository still. Please open a new issue if you encounter any issues. For now you will have to navigate the repo yourself until I complete the readme.md, create your scrape_config file, run launcher.py, if you hit any issues hopefully the code tells you what went wrong. 

Additionally, I would appreciate it if you could star/share the repository with anyone who might find it useful - normally wouldn't ask but I put in a lot of work to fix this whilst creating an extendable framework.

**Comment by eltesco1** [comment]
Sure, Thanks Jamal, 

I will share with those doing research projects in my Business Degree, its such a fantastic tool.

I am still getting errors as below. I Have a solid and fast internet connection but it seems to fail after scraping a few items (number changes each time). See below:

C:\Users\Admin\Downloads\pyscrapify-main (1)\pyscrapify-main>launcher.py
[-] Preparing to launch scraper...
[i] Generated output name: result_0
[?] Please select a scraper configuration: test.json
 > test.json

[-] Calling scraper launcher...
[i] Running Selenium driver without header...
[i] Disabled Selenium driver logging...
[i] Loaded test.json contents:
DXC Technology: https://www.seek.com.au/companies/dxc-technology-797000/reviews
[-] Scraping DXC Technology
16it [01:15,  4.74s/it]
[!] ALERT: Error occurred, ending Selenium driver session...
[!] ERROR: Unexpected error: could be internet...
scraper:Seek TimeoutException
Message:

[!] TRACE:
  File "C:\Users\Admin\Downloads\pyscrapify-main (1)\pyscrapify-main\utilities\scraper_controller.py", line 101, in scrape_launch
    scrape_website(driver, scraper, config)
  File "C:\Users\Admin\Downloads\pyscrapify-main (1)\pyscrapify-main\utilities\scraper_controller.py", line 88, in scrape_website
    data_blocks = scrape_data(driver, scraper, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Downloads\pyscrapify-main (1)\pyscrapify-main\utilities\scraper_controller.py", line 72, in scrape_data
    SE.handle_bad_data(scraper.navigators.wait_for_page, config.data_strict, driver)
  File "C:\Users\Admin\Downloads\pyscrapify-main (1)\pyscrapify-main\utilities\custom_exceptions.py", line 35, in handle_bad_data
    func(*args, **kwargs)
  File "C:\Users\Admin\Downloads\pyscrapify-main (1)\pyscrapify-main\scrapers\Seek.py", line 133, in wait_for_page
    wait.until(page_has_changed)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)

[*] DUMP:
{'data_strict': True,
 'orgs': [{'name': 'DXC Technology',
           'url': 'https://www.seek.com.au/companies/dxc-technology-797000/reviews'}],
 'output_name': 'result_0',
 'scraper_name': 'Seek',
 'selenium_header': False,
 'selenium_logging': False}

**Comment by eltesco1** [comment]
I have also tried two different internet connections the one at my workplace is 100Mbts
